name: Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ created ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: ['1.21', '1.22']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v -race -coverprofile=coverage.out ./...

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      if: matrix.os == 'ubuntu-latest' && matrix.go == '1.21'
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build for all platforms
      run: |
        # Windows
        GOOS=windows GOARCH=amd64 go build -o build/sterm-windows-amd64.exe .
        GOOS=windows GOARCH=386 go build -o build/sterm-windows-386.exe .

        # Linux
        GOOS=linux GOARCH=amd64 go build -o build/sterm-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -o build/sterm-linux-arm64 .
        GOOS=linux GOARCH=arm go build -o build/sterm-linux-arm .

        # macOS
        GOOS=darwin GOARCH=amd64 go build -o build/sterm-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -o build/sterm-darwin-arm64 .

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: build/

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: binaries
        path: build/

    - name: Create release archives
      run: |
        VERSION=${{ github.event.release.tag_name }}
        mkdir -p releases

        # Package Windows releases
        cd build
        zip ../releases/sterm-${VERSION}-windows-amd64.zip sterm-windows-amd64.exe
        zip ../releases/sterm-${VERSION}-windows-386.zip sterm-windows-386.exe

        # Package Linux releases
        tar -czf ../releases/sterm-${VERSION}-linux-amd64.tar.gz sterm-linux-amd64
        tar -czf ../releases/sterm-${VERSION}-linux-arm64.tar.gz sterm-linux-arm64
        tar -czf ../releases/sterm-${VERSION}-linux-arm.tar.gz sterm-linux-arm

        # Package macOS releases
        tar -czf ../releases/sterm-${VERSION}-darwin-amd64.tar.gz sterm-darwin-amd64
        tar -czf ../releases/sterm-${VERSION}-darwin-arm64.tar.gz sterm-darwin-arm64

        cd ..

        # Create checksums
        cd releases
        sha256sum * > checksums.txt

    - name: Upload release assets
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          const releaseId = context.payload.release.id;
          const releasesDir = 'releases';

          const files = fs.readdirSync(releasesDir);

          for (const file of files) {
            const filePath = path.join(releasesDir, file);
            const fileContent = fs.readFileSync(filePath);

            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId,
              name: file,
              data: fileContent
            });
          }